import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
export default function Home() {
	const [value,setValue]=useState("")
	const [response,setResponse]=useState("")

	const handleSubmit= ()=>{
		console.log(value);
		axios.get(
			`/api/check?number=${value}`
		  )
		  .then((res) => {
			if (res.status === 200) {
			  const response = res.data.data;
			  if (response) {
				 console.log('response:', response);
				setResponse(response);
			  } else {
				  console.log("errpr");
			  }
			} 
		  })
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<input type="text" value={value} onChange={e=>setValue(e.target.value)} />
				<button onClick={handleSubmit}>check</button>
			</main>
		</div>
	);
}
